name: Build and Package KuChu

on:
  - push:
      branches:
        - "master"
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  
    - name: Zipping
      run: |
        zip -r KuChu.osk *
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: KuChu.osk
        path: ./KuChu.osk
  Release:
    name: Create Game Release
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ needs.windows-build.result == 'success' }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set RELEASE
      run: echo $(date +'%Y.%m.%d') > RELEASE
    - name: Download de artifacts
      uses: actions/download-artifact@v4
      with:
          name: KuChu.osk
    - name: Get current date for Release
      id: date
      run: echo "::set-output name=date::$(date +'%Y.%m.%d')"
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: KuChu ${{ steps.date.outputs.date }}
        tag_name: ${{ steps.date.outputs.date }} 
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: upload KuChu
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: KuChu.osk
        asset_name: KuChu.osk
        asset_content_type: application/octet-stream
